### ISSUE TITLE
Which is collect, <multset value expression> or <multiset value expression>

### ISSUE THREAD

**Issue by GCer-Hidenori** [ronsavage/SQL#16]
I just found typo of &lt;multset value expression> or &lt;multiset value expression> .
In sql-2003-2.bnf,the below lines uses &lt;multset value expression> but no definition in BNF.
`<multiset element reference> ::=`
`		ELEMENT <left paren> <multset value expression> <right paren>`

But there is &lt;multiset value expression> definition in BNF.
`<multiset value expression> ::=`
`		<multiset term>`
`	|	<multiset value expression> MULTISET UNION [ ALL | DISTINCT ] <multiset term>`
`	|	<multiset value expression> MULTISET EXCEPT [ ALL | DISTINCT ] <multiset term>`

**Comment by ronsavage** [comment]
It must be a typo for <multiset value expression>. I scanned the repo and there is only 1 reference to multset, in sql-2003-2.bnf, and 1 on the corresponding sql-2003-2.bnf.html.
Are you able to edit the latter file too?

**Comment by ronsavage** [comment]
Oops. Typo in my msg about typos! Should have been:
It must be a typo for multiset.

**Comment by GCer-Hidenori** [comment]
Of course.
I sent pull request.
please check it.
https://github.com/ronsavage/SQL/pull/18
