### ISSUE TITLE
[typo]typo for module collations

### ISSUE THREAD

**Issue by GCer-Hidenori** [ronsavage/SQL#19]
At line 4472 of sql-2003-2.bnf,`<module collation>` may be typo for `<module collations>`.

```
<SQL-client module definition> ::=
		<module name clause> <language clause> <module authorization clause>
		[ <module path specification> ]
		[ <module transform group specification> ]
		[ <module collation> ]
		~~~~~~here~~~~~~~~~~~~~~~~
		[ <temporary table declaration>... ]
		<module contents>...
```

At line 4487 of sql-2003-2.bnf,`<module collations>` is defined,but `<module collation>` is not found.
```
<module collations> ::= <module collation specification>...
```

**Comment by ronsavage** [comment]
Hi

Looking at the usages of that term, I would prefer altering lines 4487
and 5753 to use 'module collation', i.e. in the singular.

The reason for my decision is that on line 4487 there is an ellipsis
(...) which indicates plural/repetition elsewhere in the doc. See lines
4421 and 4446 (and elsewhere) for example, and they don't use plural
terminology.

What do you think?

---
Ron Savage
savage.net.au 
On 2020-03-10 22:25, GCer-Hidenori wrote:

> At line 4472 of sql-2003-2.bnf,<module collation> may be typo for <module collations>.
> 
> <SQL-client module definition> ::=
> <module name clause> <language clause> <module authorization clause>
> [ <module path specification> ]
> [ <module transform group specification> ]
> [ <module collation> ]
> ~~~~~~here~~~~~~~~~~~~~~~~
> [ <temporary table declaration>... ]
> <module contents>...
> 
> At line 4487 of sql-2003-2.bnf,<module collations> is defined,but <module collation> is not found.
> 
> <module collations> ::= <module collation specification>...
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/ronsavage/SQL/issues/19?email_source=notifications&amp;email_token=AAAFH6EMRMU756ATF5OIMOTRGYPSVA5CNFSM4LE4XDZKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IT3MMUQ
[2]
