### ISSUE TITLE
Definition of <overlaps predicate part> not found.

### ISSUE THREAD

**Issue by GCer-Hidenori** [ronsavage/SQL#21]
At line 1539 of sql-2003-2.bnf,`<overlaps predicate part>` is used.
But there is no definition of `<overlaps predicate part>`.

**Comment by ronsavage** [comment]
Hi

Agreed. After examining line 2771 I suggest changing line 1539 from:
<overlaps predicate part>
To:
<overlaps predicate>

---
Ron Savage
savage.net.au 
On 2020-03-13 00:49, GCer-Hidenori wrote:

> At line 1539 of sql-2003-2.bnf,<overlaps predicate part> is used.
> But there is no definition of <overlaps predicate part>. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/ronsavage/SQL/issues/21
[2]
