### ISSUE TITLE
asterisk

### ISSUE THREAD

**Issue by JEROME-TICTEC** [ronsavage/SQL#22]
Hi all,
at sql-2003-2.bnf.html#select list:

`<select list>    ::=   <asterisk> | <select sublist> [ { <comma> <select sublist> }... ] `
mean `<asterisk> **or** <select sublist> [ { <comma> <select sublist> }... ] `
but SQL accept : 
 `<select list>    ::=  <asterisk> | <asterisk> <select sublist> [ { <comma> <select sublist> }... ]  `
regards

**Comment by ronsavage** [comment]
Thanx.
Where did you get that 'SQL accept' definition from?

**Comment by JEROME-TICTEC** [comment]
unfortunately I do not have access to official ISO standard.
I would say "any SQL engine, accept..." 

Regards

**Comment by ronsavage** [comment]
Here are the [Postgresql docs](https://www.postgresql.org/docs/).
And here are their [select lists](https://www.postgresql.org/docs/12/queries-select-lists.html).
I've read the latter doc, and can see no possibility of allowing the syntax you specified above, i.e.:
<select list> ::= <asterisk> | <asterisk> <select sublist> [ { <comma> <select sublist> }... ]

So my recommendation is to chop the 2nd usage of <asterisk> in that line.

**Comment by JEROME-TICTEC** [comment]
> When working with multiple tables, it can also be useful to ask for all the columns of a particular table: SELECT tbl1.*, tbl2.a FROM ...

so in case of multiple tables you can find **asterisk** into **select sublist**.

Oracle accept : SELECT *, a FROM ...    whatever  number of tables.

What is ISO recommendation ?

**Comment by JEROME-TICTEC** [comment]
it looks ok, because **select sublist** purpose **qualified asterisk**

**Comment by ronsavage** [comment]
Hi

Ah, yes.

---
Ron Savage
savage.net.au 
On 2020-03-15 13:08, JEROME-TICTEC wrote:

>> When working with multiple tables, it can also be useful to ask for all the columns of a particular table: SELECT tbl1.*, tbl2.a FROM ...
> 
> so in case of multiple tables you can find ASTERISK into SELECT SUBLIST. 
> 
> Oracle accept : SELECT *, a FROM ... whatever number of tables. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/ronsavage/SQL/issues/22#issuecomment-599158020
[2]

**Comment by ronsavage** [comment]
Hi

ISO is https://www.iso.org/standard/45498.html

---
Ron Savage
savage.net.au 
On 2020-03-15 13:19, JEROME-TICTEC wrote:

> it looks ok, because SELECT SUBLIST purpose QUALIFIED ASTERISK 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/ronsavage/SQL/issues/22#issuecomment-599158642
[2]

**Comment by ronsavage** [comment]
Hi

I finally found one which has not been withdrawn:
https://www.iso.org/standard/63555.html

CHF 178 is about $AUD 310! The problem with spending this amount of
money is that it may not provide an answer. 

Scroll right down to 'REVISIONS / CORRIGENDA' and you'll a new version
is under development. 

And anyway, we're editing a 2003 version whereas the current one is
2016.

I'll post a blog item on blogs.perl.org and see if anyone cares to vote
on this matter.

---

Ron Savage
savage.net.au 
On 2020-03-15 13:19, JEROME-TICTEC wrote:

> it looks ok, because SELECT SUBLIST purpose QUALIFIED ASTERISK 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/ronsavage/SQL/issues/22#issuecomment-599158642
[2]

**Comment by ronsavage** [comment]
This version
`<select list> ::= <asterisk> | <asterisk> <select sublist> [ { <comma> <select sublist> }... ]`
Has to be wrong because it allows an asterisk /not/ followed by a comma.

**Comment by JEROME-TICTEC** [comment]
i would like to say:
 actual `<select list> ::= <asterisk> | <select sublist> [ { <comma> <select sublist> }... ] ,`  is ok
because i founded **QUALIFIED ASTERISK** into  **SELECT SUBLIST**

**Comment by ronsavage** [comment]
Yes,  that's fine by me.
Thanx.
