### ISSUE TITLE
unclosed h2 tags -- 

### ISSUE THREAD

**Issue by readytheory** [ronsavage/SQL#6]
Starting at line 5330 of sql-2003-2.bnf (the plaintext one), there are a few unclosed "--h2" tags.  (would expect to see a --/h2 for each)

**Comment by jleffler** [comment]
Agreed.  There's one missing after 5330, and one missing after 6392.  There are no `--h1` or `--h4` tags; the remaining `--h2` and `--h3` tags are properly paired in all the `*.bnf` files.
